syntax = "proto3";

package link;

option go_package = "./pb";

service Link {
  rpc Shorten(ShortenRequest) returns (ShortenResponse);
  rpc Redirect(RedirectRequest) returns (RedirectResponse);
}

message ShortenRequest {
  string long_url    = 1;
  string custom_code = 2;
  int64  expire_at   = 3;
  string password    = 4;
}

message ShortenResponse {
  string short_code = 1;
  string short_url  = 2;
}

message RedirectRequest {
  string short_code = 1;
  // 访问来源信息，由网关从 HTTP 请求提取，用于访问日志统计。
  string ip         = 2;
  string user_agent = 3;
  string referer    = 4;
}

message RedirectResponse {
  string long_url = 1;
}
