// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: link.proto

package server

import (
	"context"

	"golink/rpc/link/internal/logic"
	"golink/rpc/link/internal/svc"
	"golink/rpc/link/pb"
)

type LinkServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLinkServer
}

func NewLinkServer(svcCtx *svc.ServiceContext) *LinkServer {
	return &LinkServer{
		svcCtx: svcCtx,
	}
}

func (s *LinkServer) Shorten(ctx context.Context, in *pb.ShortenRequest) (*pb.ShortenResponse, error) {
	l := logic.NewShortenLogic(ctx, s.svcCtx)
	return l.Shorten(in)
}

func (s *LinkServer) Redirect(ctx context.Context, in *pb.RedirectRequest) (*pb.RedirectResponse, error) {
	l := logic.NewRedirectLogic(ctx, s.svcCtx)
	return l.Redirect(in)
}
