// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type RedirectResp struct {
	LongURL string `json:"long_url"`
}

type ShortenReq struct {
	URL        string `json:"url"`
	CustomCode string `json:"custom_code,optional"`
	ExpireAt   int64  `json:"expire_at,optional"`
	Password   string `json:"password,optional"`
}

type ShortenResp struct {
	ShortURL string `json:"short_url"`
	Code     string `json:"code"`
}

type StatsResp struct {
	Code       string `json:"short_code"`
	LongURL    string `json:"long_url"`
	ClickCount uint64 `json:"click_count"`
	PV         int32  `json:"pv"`
	UV         int32  `json:"uv"`
}
