// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: link.proto

package link

import (
	"context"

	"golink/rpc/link/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RedirectRequest  = pb.RedirectRequest
	RedirectResponse = pb.RedirectResponse
	ShortenRequest   = pb.ShortenRequest
	ShortenResponse  = pb.ShortenResponse

	Link interface {
		Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error)
		Redirect(ctx context.Context, in *RedirectRequest, opts ...grpc.CallOption) (*RedirectResponse, error)
	}

	defaultLink struct {
		cli zrpc.Client
	}
)

func NewLink(cli zrpc.Client) Link {
	return &defaultLink{
		cli: cli,
	}
}

func (m *defaultLink) Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenResponse, error) {
	client := pb.NewLinkClient(m.cli.Conn())
	return client.Shorten(ctx, in, opts...)
}

func (m *defaultLink) Redirect(ctx context.Context, in *RedirectRequest, opts ...grpc.CallOption) (*RedirectResponse, error) {
	client := pb.NewLinkClient(m.cli.Conn())
	return client.Redirect(ctx, in, opts...)
}
